id: AC6232C9C
base_file: f49EB.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:57:00.129181
  last_modified_at: 2022-06-05 19:57:00.129191
